// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.buff.proto

package game.msg;

public final class MsgBuff {
  private MsgBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SCBuffAddOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 objId = 1;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    boolean hasObjId();
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    long getObjId();

    // optional .game.msg.DBuff buff = 2;
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    boolean hasBuff();
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    game.msg.Define.DBuff getBuff();
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    game.msg.Define.DBuffOrBuilder getBuffOrBuilder();
  }
  /**
   * Protobuf type {@code game.msg.SCBuffAdd}
   *
   * <pre>
   *增加新Buff（群发）
   * </pre>
   */
  public static final class SCBuffAdd extends
      com.google.protobuf.GeneratedMessage
      implements SCBuffAddOrBuilder {
    // Use SCBuffAdd.newBuilder() to construct.
    private SCBuffAdd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCBuffAdd(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCBuffAdd defaultInstance;
    public static SCBuffAdd getDefaultInstance() {
      return defaultInstance;
    }

    public SCBuffAdd getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCBuffAdd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              objId_ = input.readInt64();
              break;
            }
            case 18: {
              game.msg.Define.DBuff.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = buff_.toBuilder();
              }
              buff_ = input.readMessage(game.msg.Define.DBuff.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(buff_);
                buff_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffAdd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffAdd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgBuff.SCBuffAdd.class, game.msg.MsgBuff.SCBuffAdd.Builder.class);
    }

    public static com.google.protobuf.Parser<SCBuffAdd> PARSER =
        new com.google.protobuf.AbstractParser<SCBuffAdd>() {
      public SCBuffAdd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCBuffAdd(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCBuffAdd> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 objId = 1;
    public static final int OBJID_FIELD_NUMBER = 1;
    private long objId_;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public boolean hasObjId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public long getObjId() {
      return objId_;
    }

    // optional .game.msg.DBuff buff = 2;
    public static final int BUFF_FIELD_NUMBER = 2;
    private game.msg.Define.DBuff buff_;
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public boolean hasBuff() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public game.msg.Define.DBuff getBuff() {
      return buff_;
    }
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public game.msg.Define.DBuffOrBuilder getBuffOrBuilder() {
      return buff_;
    }

    private void initFields() {
      objId_ = 0L;
      buff_ = game.msg.Define.DBuff.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, buff_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, buff_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffAdd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgBuff.SCBuffAdd prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCBuffAdd}
     *
     * <pre>
     *增加新Buff（群发）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgBuff.SCBuffAddOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffAdd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffAdd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgBuff.SCBuffAdd.class, game.msg.MsgBuff.SCBuffAdd.Builder.class);
      }

      // Construct using game.msg.MsgBuff.SCBuffAdd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuffFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (buffBuilder_ == null) {
          buff_ = game.msg.Define.DBuff.getDefaultInstance();
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffAdd_descriptor;
      }

      public game.msg.MsgBuff.SCBuffAdd getDefaultInstanceForType() {
        return game.msg.MsgBuff.SCBuffAdd.getDefaultInstance();
      }

      public game.msg.MsgBuff.SCBuffAdd build() {
        game.msg.MsgBuff.SCBuffAdd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgBuff.SCBuffAdd buildPartial() {
        game.msg.MsgBuff.SCBuffAdd result = new game.msg.MsgBuff.SCBuffAdd(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objId_ = objId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (buffBuilder_ == null) {
          result.buff_ = buff_;
        } else {
          result.buff_ = buffBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgBuff.SCBuffAdd) {
          return mergeFrom((game.msg.MsgBuff.SCBuffAdd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgBuff.SCBuffAdd other) {
        if (other == game.msg.MsgBuff.SCBuffAdd.getDefaultInstance()) return this;
        if (other.hasObjId()) {
          setObjId(other.getObjId());
        }
        if (other.hasBuff()) {
          mergeBuff(other.getBuff());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgBuff.SCBuffAdd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgBuff.SCBuffAdd) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 objId = 1;
      private long objId_ ;
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public boolean hasObjId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public long getObjId() {
        return objId_;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder setObjId(long value) {
        bitField0_ |= 0x00000001;
        objId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder clearObjId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objId_ = 0L;
        onChanged();
        return this;
      }

      // optional .game.msg.DBuff buff = 2;
      private game.msg.Define.DBuff buff_ = game.msg.Define.DBuff.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder> buffBuilder_;
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public boolean hasBuff() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuff getBuff() {
        if (buffBuilder_ == null) {
          return buff_;
        } else {
          return buffBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder setBuff(game.msg.Define.DBuff value) {
        if (buffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buff_ = value;
          onChanged();
        } else {
          buffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder setBuff(
          game.msg.Define.DBuff.Builder builderForValue) {
        if (buffBuilder_ == null) {
          buff_ = builderForValue.build();
          onChanged();
        } else {
          buffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder mergeBuff(game.msg.Define.DBuff value) {
        if (buffBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              buff_ != game.msg.Define.DBuff.getDefaultInstance()) {
            buff_ =
              game.msg.Define.DBuff.newBuilder(buff_).mergeFrom(value).buildPartial();
          } else {
            buff_ = value;
          }
          onChanged();
        } else {
          buffBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder clearBuff() {
        if (buffBuilder_ == null) {
          buff_ = game.msg.Define.DBuff.getDefaultInstance();
          onChanged();
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuff.Builder getBuffBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBuffFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuffOrBuilder getBuffOrBuilder() {
        if (buffBuilder_ != null) {
          return buffBuilder_.getMessageOrBuilder();
        } else {
          return buff_;
        }
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder> 
          getBuffFieldBuilder() {
        if (buffBuilder_ == null) {
          buffBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder>(
                  buff_,
                  getParentForChildren(),
                  isClean());
          buff_ = null;
        }
        return buffBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCBuffAdd)
    }

    static {
      defaultInstance = new SCBuffAdd(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCBuffAdd)
  }

  public interface SCBuffUpdateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 objId = 1;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    boolean hasObjId();
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    long getObjId();

    // optional .game.msg.DBuff buff = 2;
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    boolean hasBuff();
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    game.msg.Define.DBuff getBuff();
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    game.msg.Define.DBuffOrBuilder getBuffOrBuilder();
  }
  /**
   * Protobuf type {@code game.msg.SCBuffUpdate}
   *
   * <pre>
   *Buff更新（群发）
   * </pre>
   */
  public static final class SCBuffUpdate extends
      com.google.protobuf.GeneratedMessage
      implements SCBuffUpdateOrBuilder {
    // Use SCBuffUpdate.newBuilder() to construct.
    private SCBuffUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCBuffUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCBuffUpdate defaultInstance;
    public static SCBuffUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public SCBuffUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCBuffUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              objId_ = input.readInt64();
              break;
            }
            case 18: {
              game.msg.Define.DBuff.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = buff_.toBuilder();
              }
              buff_ = input.readMessage(game.msg.Define.DBuff.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(buff_);
                buff_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgBuff.SCBuffUpdate.class, game.msg.MsgBuff.SCBuffUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<SCBuffUpdate> PARSER =
        new com.google.protobuf.AbstractParser<SCBuffUpdate>() {
      public SCBuffUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCBuffUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCBuffUpdate> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 objId = 1;
    public static final int OBJID_FIELD_NUMBER = 1;
    private long objId_;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public boolean hasObjId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public long getObjId() {
      return objId_;
    }

    // optional .game.msg.DBuff buff = 2;
    public static final int BUFF_FIELD_NUMBER = 2;
    private game.msg.Define.DBuff buff_;
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public boolean hasBuff() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public game.msg.Define.DBuff getBuff() {
      return buff_;
    }
    /**
     * <code>optional .game.msg.DBuff buff = 2;</code>
     *
     * <pre>
     *Buff信息
     * </pre>
     */
    public game.msg.Define.DBuffOrBuilder getBuffOrBuilder() {
      return buff_;
    }

    private void initFields() {
      objId_ = 0L;
      buff_ = game.msg.Define.DBuff.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, buff_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, buff_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgBuff.SCBuffUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCBuffUpdate}
     *
     * <pre>
     *Buff更新（群发）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgBuff.SCBuffUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgBuff.SCBuffUpdate.class, game.msg.MsgBuff.SCBuffUpdate.Builder.class);
      }

      // Construct using game.msg.MsgBuff.SCBuffUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBuffFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (buffBuilder_ == null) {
          buff_ = game.msg.Define.DBuff.getDefaultInstance();
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffUpdate_descriptor;
      }

      public game.msg.MsgBuff.SCBuffUpdate getDefaultInstanceForType() {
        return game.msg.MsgBuff.SCBuffUpdate.getDefaultInstance();
      }

      public game.msg.MsgBuff.SCBuffUpdate build() {
        game.msg.MsgBuff.SCBuffUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgBuff.SCBuffUpdate buildPartial() {
        game.msg.MsgBuff.SCBuffUpdate result = new game.msg.MsgBuff.SCBuffUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objId_ = objId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (buffBuilder_ == null) {
          result.buff_ = buff_;
        } else {
          result.buff_ = buffBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgBuff.SCBuffUpdate) {
          return mergeFrom((game.msg.MsgBuff.SCBuffUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgBuff.SCBuffUpdate other) {
        if (other == game.msg.MsgBuff.SCBuffUpdate.getDefaultInstance()) return this;
        if (other.hasObjId()) {
          setObjId(other.getObjId());
        }
        if (other.hasBuff()) {
          mergeBuff(other.getBuff());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgBuff.SCBuffUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgBuff.SCBuffUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 objId = 1;
      private long objId_ ;
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public boolean hasObjId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public long getObjId() {
        return objId_;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder setObjId(long value) {
        bitField0_ |= 0x00000001;
        objId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder clearObjId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objId_ = 0L;
        onChanged();
        return this;
      }

      // optional .game.msg.DBuff buff = 2;
      private game.msg.Define.DBuff buff_ = game.msg.Define.DBuff.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder> buffBuilder_;
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public boolean hasBuff() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuff getBuff() {
        if (buffBuilder_ == null) {
          return buff_;
        } else {
          return buffBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder setBuff(game.msg.Define.DBuff value) {
        if (buffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buff_ = value;
          onChanged();
        } else {
          buffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder setBuff(
          game.msg.Define.DBuff.Builder builderForValue) {
        if (buffBuilder_ == null) {
          buff_ = builderForValue.build();
          onChanged();
        } else {
          buffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder mergeBuff(game.msg.Define.DBuff value) {
        if (buffBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              buff_ != game.msg.Define.DBuff.getDefaultInstance()) {
            buff_ =
              game.msg.Define.DBuff.newBuilder(buff_).mergeFrom(value).buildPartial();
          } else {
            buff_ = value;
          }
          onChanged();
        } else {
          buffBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public Builder clearBuff() {
        if (buffBuilder_ == null) {
          buff_ = game.msg.Define.DBuff.getDefaultInstance();
          onChanged();
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuff.Builder getBuffBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBuffFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      public game.msg.Define.DBuffOrBuilder getBuffOrBuilder() {
        if (buffBuilder_ != null) {
          return buffBuilder_.getMessageOrBuilder();
        } else {
          return buff_;
        }
      }
      /**
       * <code>optional .game.msg.DBuff buff = 2;</code>
       *
       * <pre>
       *Buff信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder> 
          getBuffFieldBuilder() {
        if (buffBuilder_ == null) {
          buffBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              game.msg.Define.DBuff, game.msg.Define.DBuff.Builder, game.msg.Define.DBuffOrBuilder>(
                  buff_,
                  getParentForChildren(),
                  isClean());
          buff_ = null;
        }
        return buffBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCBuffUpdate)
    }

    static {
      defaultInstance = new SCBuffUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCBuffUpdate)
  }

  public interface SCBuffDispelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 objId = 1;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    boolean hasObjId();
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    long getObjId();

    // optional int32 sn = 2;
    /**
     * <code>optional int32 sn = 2;</code>
     *
     * <pre>
     *需要移出的buffSn
     * </pre>
     */
    boolean hasSn();
    /**
     * <code>optional int32 sn = 2;</code>
     *
     * <pre>
     *需要移出的buffSn
     * </pre>
     */
    int getSn();
  }
  /**
   * Protobuf type {@code game.msg.SCBuffDispel}
   *
   * <pre>
   *Buff消失（群发）
   * </pre>
   */
  public static final class SCBuffDispel extends
      com.google.protobuf.GeneratedMessage
      implements SCBuffDispelOrBuilder {
    // Use SCBuffDispel.newBuilder() to construct.
    private SCBuffDispel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCBuffDispel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCBuffDispel defaultInstance;
    public static SCBuffDispel getDefaultInstance() {
      return defaultInstance;
    }

    public SCBuffDispel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCBuffDispel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              objId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffDispel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgBuff.internal_static_game_msg_SCBuffDispel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgBuff.SCBuffDispel.class, game.msg.MsgBuff.SCBuffDispel.Builder.class);
    }

    public static com.google.protobuf.Parser<SCBuffDispel> PARSER =
        new com.google.protobuf.AbstractParser<SCBuffDispel>() {
      public SCBuffDispel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCBuffDispel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCBuffDispel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 objId = 1;
    public static final int OBJID_FIELD_NUMBER = 1;
    private long objId_;
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public boolean hasObjId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 objId = 1;</code>
     *
     * <pre>
     *单元Id
     * </pre>
     */
    public long getObjId() {
      return objId_;
    }

    // optional int32 sn = 2;
    public static final int SN_FIELD_NUMBER = 2;
    private int sn_;
    /**
     * <code>optional int32 sn = 2;</code>
     *
     * <pre>
     *需要移出的buffSn
     * </pre>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 sn = 2;</code>
     *
     * <pre>
     *需要移出的buffSn
     * </pre>
     */
    public int getSn() {
      return sn_;
    }

    private void initFields() {
      objId_ = 0L;
      sn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, objId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.SCBuffDispel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgBuff.SCBuffDispel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCBuffDispel}
     *
     * <pre>
     *Buff消失（群发）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgBuff.SCBuffDispelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffDispel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffDispel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgBuff.SCBuffDispel.class, game.msg.MsgBuff.SCBuffDispel.Builder.class);
      }

      // Construct using game.msg.MsgBuff.SCBuffDispel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        objId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgBuff.internal_static_game_msg_SCBuffDispel_descriptor;
      }

      public game.msg.MsgBuff.SCBuffDispel getDefaultInstanceForType() {
        return game.msg.MsgBuff.SCBuffDispel.getDefaultInstance();
      }

      public game.msg.MsgBuff.SCBuffDispel build() {
        game.msg.MsgBuff.SCBuffDispel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgBuff.SCBuffDispel buildPartial() {
        game.msg.MsgBuff.SCBuffDispel result = new game.msg.MsgBuff.SCBuffDispel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.objId_ = objId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sn_ = sn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgBuff.SCBuffDispel) {
          return mergeFrom((game.msg.MsgBuff.SCBuffDispel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgBuff.SCBuffDispel other) {
        if (other == game.msg.MsgBuff.SCBuffDispel.getDefaultInstance()) return this;
        if (other.hasObjId()) {
          setObjId(other.getObjId());
        }
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgBuff.SCBuffDispel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgBuff.SCBuffDispel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 objId = 1;
      private long objId_ ;
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public boolean hasObjId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public long getObjId() {
        return objId_;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder setObjId(long value) {
        bitField0_ |= 0x00000001;
        objId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 objId = 1;</code>
       *
       * <pre>
       *单元Id
       * </pre>
       */
      public Builder clearObjId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        objId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 sn = 2;
      private int sn_ ;
      /**
       * <code>optional int32 sn = 2;</code>
       *
       * <pre>
       *需要移出的buffSn
       * </pre>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 sn = 2;</code>
       *
       * <pre>
       *需要移出的buffSn
       * </pre>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>optional int32 sn = 2;</code>
       *
       * <pre>
       *需要移出的buffSn
       * </pre>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000002;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sn = 2;</code>
       *
       * <pre>
       *需要移出的buffSn
       * </pre>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCBuffDispel)
    }

    static {
      defaultInstance = new SCBuffDispel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCBuffDispel)
  }

  public interface CSBuffDispelByHumanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 sn = 1;
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     *Buff SN
     * </pre>
     */
    boolean hasSn();
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     *Buff SN
     * </pre>
     */
    int getSn();
  }
  /**
   * Protobuf type {@code game.msg.CSBuffDispelByHuman}
   *
   * <pre>
   *手动取消Buff
   * </pre>
   */
  public static final class CSBuffDispelByHuman extends
      com.google.protobuf.GeneratedMessage
      implements CSBuffDispelByHumanOrBuilder {
    // Use CSBuffDispelByHuman.newBuilder() to construct.
    private CSBuffDispelByHuman(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSBuffDispelByHuman(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSBuffDispelByHuman defaultInstance;
    public static CSBuffDispelByHuman getDefaultInstance() {
      return defaultInstance;
    }

    public CSBuffDispelByHuman getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSBuffDispelByHuman(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sn_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgBuff.internal_static_game_msg_CSBuffDispelByHuman_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgBuff.internal_static_game_msg_CSBuffDispelByHuman_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgBuff.CSBuffDispelByHuman.class, game.msg.MsgBuff.CSBuffDispelByHuman.Builder.class);
    }

    public static com.google.protobuf.Parser<CSBuffDispelByHuman> PARSER =
        new com.google.protobuf.AbstractParser<CSBuffDispelByHuman>() {
      public CSBuffDispelByHuman parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSBuffDispelByHuman(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSBuffDispelByHuman> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 sn = 1;
    public static final int SN_FIELD_NUMBER = 1;
    private int sn_;
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     *Buff SN
     * </pre>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sn = 1;</code>
     *
     * <pre>
     *Buff SN
     * </pre>
     */
    public int getSn() {
      return sn_;
    }

    private void initFields() {
      sn_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgBuff.CSBuffDispelByHuman parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgBuff.CSBuffDispelByHuman prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.CSBuffDispelByHuman}
     *
     * <pre>
     *手动取消Buff
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgBuff.CSBuffDispelByHumanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgBuff.internal_static_game_msg_CSBuffDispelByHuman_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgBuff.internal_static_game_msg_CSBuffDispelByHuman_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgBuff.CSBuffDispelByHuman.class, game.msg.MsgBuff.CSBuffDispelByHuman.Builder.class);
      }

      // Construct using game.msg.MsgBuff.CSBuffDispelByHuman.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgBuff.internal_static_game_msg_CSBuffDispelByHuman_descriptor;
      }

      public game.msg.MsgBuff.CSBuffDispelByHuman getDefaultInstanceForType() {
        return game.msg.MsgBuff.CSBuffDispelByHuman.getDefaultInstance();
      }

      public game.msg.MsgBuff.CSBuffDispelByHuman build() {
        game.msg.MsgBuff.CSBuffDispelByHuman result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgBuff.CSBuffDispelByHuman buildPartial() {
        game.msg.MsgBuff.CSBuffDispelByHuman result = new game.msg.MsgBuff.CSBuffDispelByHuman(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgBuff.CSBuffDispelByHuman) {
          return mergeFrom((game.msg.MsgBuff.CSBuffDispelByHuman)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgBuff.CSBuffDispelByHuman other) {
        if (other == game.msg.MsgBuff.CSBuffDispelByHuman.getDefaultInstance()) return this;
        if (other.hasSn()) {
          setSn(other.getSn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgBuff.CSBuffDispelByHuman parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgBuff.CSBuffDispelByHuman) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 sn = 1;
      private int sn_ ;
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       *Buff SN
       * </pre>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       *Buff SN
       * </pre>
       */
      public int getSn() {
        return sn_;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       *Buff SN
       * </pre>
       */
      public Builder setSn(int value) {
        bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sn = 1;</code>
       *
       * <pre>
       *Buff SN
       * </pre>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.CSBuffDispelByHuman)
    }

    static {
      defaultInstance = new CSBuffDispelByHuman(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.CSBuffDispelByHuman)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCBuffAdd_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCBuffAdd_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCBuffUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCBuffUpdate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCBuffDispel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCBuffDispel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_CSBuffDispelByHuman_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_CSBuffDispelByHuman_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016msg.buff.proto\022\010game.msg\032\roptions.prot" +
      "o\032\014define.proto\"@\n\tSCBuffAdd\022\r\n\005objId\030\001 " +
      "\001(\003\022\035\n\004buff\030\002 \001(\0132\017.game.msg.DBuff:\005\210\303\032\212" +
      "\016\"C\n\014SCBuffUpdate\022\r\n\005objId\030\001 \001(\003\022\035\n\004buff" +
      "\030\002 \001(\0132\017.game.msg.DBuff:\005\210\303\032\213\016\"0\n\014SCBuff" +
      "Dispel\022\r\n\005objId\030\001 \001(\003\022\n\n\002sn\030\002 \001(\005:\005\210\303\032\214\016" +
      "\"(\n\023CSBuffDispelByHuman\022\n\n\002sn\030\001 \001(\005:\005\210\303\032" +
      "\215\016"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_msg_SCBuffAdd_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_msg_SCBuffAdd_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCBuffAdd_descriptor,
              new java.lang.String[] { "ObjId", "Buff", });
          internal_static_game_msg_SCBuffUpdate_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_msg_SCBuffUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCBuffUpdate_descriptor,
              new java.lang.String[] { "ObjId", "Buff", });
          internal_static_game_msg_SCBuffDispel_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_game_msg_SCBuffDispel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCBuffDispel_descriptor,
              new java.lang.String[] { "ObjId", "Sn", });
          internal_static_game_msg_CSBuffDispelByHuman_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_game_msg_CSBuffDispelByHuman_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_CSBuffDispelByHuman_descriptor,
              new java.lang.String[] { "Sn", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.msg.Options.getDescriptor(),
          game.msg.Define.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
