// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.guide.proto

package game.msg;

public final class MsgGuide {
  private MsgGuide() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSChangeGuideStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 OrderIndex = 1;
    /**
     * <code>optional int32 OrderIndex = 1;</code>
     *
     * <pre>
     *新手引导：流程引导执行ID
     * </pre>
     */
    boolean hasOrderIndex();
    /**
     * <code>optional int32 OrderIndex = 1;</code>
     *
     * <pre>
     *新手引导：流程引导执行ID
     * </pre>
     */
    int getOrderIndex();

    // optional int32 CurFunctionId = 2;
    /**
     * <code>optional int32 CurFunctionId = 2;</code>
     *
     * <pre>
     *新手引导：新功能开启时新功能ID
     * </pre>
     */
    boolean hasCurFunctionId();
    /**
     * <code>optional int32 CurFunctionId = 2;</code>
     *
     * <pre>
     *新手引导：新功能开启时新功能ID
     * </pre>
     */
    int getCurFunctionId();

    // optional int32 FuncIndex = 3;
    /**
     * <code>optional int32 FuncIndex = 3;</code>
     *
     * <pre>
     *新手引导：功能开启时引导执行计数
     * </pre>
     */
    boolean hasFuncIndex();
    /**
     * <code>optional int32 FuncIndex = 3;</code>
     *
     * <pre>
     *新手引导：功能开启时引导执行计数
     * </pre>
     */
    int getFuncIndex();
  }
  /**
   * Protobuf type {@code game.msg.CSChangeGuideStatus}
   *
   * <pre>
   *前端推送的引导状态
   * </pre>
   */
  public static final class CSChangeGuideStatus extends
      com.google.protobuf.GeneratedMessage
      implements CSChangeGuideStatusOrBuilder {
    // Use CSChangeGuideStatus.newBuilder() to construct.
    private CSChangeGuideStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSChangeGuideStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSChangeGuideStatus defaultInstance;
    public static CSChangeGuideStatus getDefaultInstance() {
      return defaultInstance;
    }

    public CSChangeGuideStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSChangeGuideStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              orderIndex_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              curFunctionId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              funcIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgGuide.internal_static_game_msg_CSChangeGuideStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgGuide.internal_static_game_msg_CSChangeGuideStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgGuide.CSChangeGuideStatus.class, game.msg.MsgGuide.CSChangeGuideStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<CSChangeGuideStatus> PARSER =
        new com.google.protobuf.AbstractParser<CSChangeGuideStatus>() {
      public CSChangeGuideStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSChangeGuideStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSChangeGuideStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 OrderIndex = 1;
    public static final int ORDERINDEX_FIELD_NUMBER = 1;
    private int orderIndex_;
    /**
     * <code>optional int32 OrderIndex = 1;</code>
     *
     * <pre>
     *新手引导：流程引导执行ID
     * </pre>
     */
    public boolean hasOrderIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 OrderIndex = 1;</code>
     *
     * <pre>
     *新手引导：流程引导执行ID
     * </pre>
     */
    public int getOrderIndex() {
      return orderIndex_;
    }

    // optional int32 CurFunctionId = 2;
    public static final int CURFUNCTIONID_FIELD_NUMBER = 2;
    private int curFunctionId_;
    /**
     * <code>optional int32 CurFunctionId = 2;</code>
     *
     * <pre>
     *新手引导：新功能开启时新功能ID
     * </pre>
     */
    public boolean hasCurFunctionId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 CurFunctionId = 2;</code>
     *
     * <pre>
     *新手引导：新功能开启时新功能ID
     * </pre>
     */
    public int getCurFunctionId() {
      return curFunctionId_;
    }

    // optional int32 FuncIndex = 3;
    public static final int FUNCINDEX_FIELD_NUMBER = 3;
    private int funcIndex_;
    /**
     * <code>optional int32 FuncIndex = 3;</code>
     *
     * <pre>
     *新手引导：功能开启时引导执行计数
     * </pre>
     */
    public boolean hasFuncIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 FuncIndex = 3;</code>
     *
     * <pre>
     *新手引导：功能开启时引导执行计数
     * </pre>
     */
    public int getFuncIndex() {
      return funcIndex_;
    }

    private void initFields() {
      orderIndex_ = 0;
      curFunctionId_ = 0;
      funcIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, orderIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, curFunctionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, funcIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curFunctionId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, funcIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.CSChangeGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgGuide.CSChangeGuideStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.CSChangeGuideStatus}
     *
     * <pre>
     *前端推送的引导状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgGuide.CSChangeGuideStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgGuide.internal_static_game_msg_CSChangeGuideStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgGuide.internal_static_game_msg_CSChangeGuideStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgGuide.CSChangeGuideStatus.class, game.msg.MsgGuide.CSChangeGuideStatus.Builder.class);
      }

      // Construct using game.msg.MsgGuide.CSChangeGuideStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        curFunctionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        funcIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgGuide.internal_static_game_msg_CSChangeGuideStatus_descriptor;
      }

      public game.msg.MsgGuide.CSChangeGuideStatus getDefaultInstanceForType() {
        return game.msg.MsgGuide.CSChangeGuideStatus.getDefaultInstance();
      }

      public game.msg.MsgGuide.CSChangeGuideStatus build() {
        game.msg.MsgGuide.CSChangeGuideStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgGuide.CSChangeGuideStatus buildPartial() {
        game.msg.MsgGuide.CSChangeGuideStatus result = new game.msg.MsgGuide.CSChangeGuideStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderIndex_ = orderIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.curFunctionId_ = curFunctionId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.funcIndex_ = funcIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgGuide.CSChangeGuideStatus) {
          return mergeFrom((game.msg.MsgGuide.CSChangeGuideStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgGuide.CSChangeGuideStatus other) {
        if (other == game.msg.MsgGuide.CSChangeGuideStatus.getDefaultInstance()) return this;
        if (other.hasOrderIndex()) {
          setOrderIndex(other.getOrderIndex());
        }
        if (other.hasCurFunctionId()) {
          setCurFunctionId(other.getCurFunctionId());
        }
        if (other.hasFuncIndex()) {
          setFuncIndex(other.getFuncIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgGuide.CSChangeGuideStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgGuide.CSChangeGuideStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 OrderIndex = 1;
      private int orderIndex_ ;
      /**
       * <code>optional int32 OrderIndex = 1;</code>
       *
       * <pre>
       *新手引导：流程引导执行ID
       * </pre>
       */
      public boolean hasOrderIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 OrderIndex = 1;</code>
       *
       * <pre>
       *新手引导：流程引导执行ID
       * </pre>
       */
      public int getOrderIndex() {
        return orderIndex_;
      }
      /**
       * <code>optional int32 OrderIndex = 1;</code>
       *
       * <pre>
       *新手引导：流程引导执行ID
       * </pre>
       */
      public Builder setOrderIndex(int value) {
        bitField0_ |= 0x00000001;
        orderIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 OrderIndex = 1;</code>
       *
       * <pre>
       *新手引导：流程引导执行ID
       * </pre>
       */
      public Builder clearOrderIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderIndex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 CurFunctionId = 2;
      private int curFunctionId_ ;
      /**
       * <code>optional int32 CurFunctionId = 2;</code>
       *
       * <pre>
       *新手引导：新功能开启时新功能ID
       * </pre>
       */
      public boolean hasCurFunctionId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 CurFunctionId = 2;</code>
       *
       * <pre>
       *新手引导：新功能开启时新功能ID
       * </pre>
       */
      public int getCurFunctionId() {
        return curFunctionId_;
      }
      /**
       * <code>optional int32 CurFunctionId = 2;</code>
       *
       * <pre>
       *新手引导：新功能开启时新功能ID
       * </pre>
       */
      public Builder setCurFunctionId(int value) {
        bitField0_ |= 0x00000002;
        curFunctionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 CurFunctionId = 2;</code>
       *
       * <pre>
       *新手引导：新功能开启时新功能ID
       * </pre>
       */
      public Builder clearCurFunctionId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        curFunctionId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 FuncIndex = 3;
      private int funcIndex_ ;
      /**
       * <code>optional int32 FuncIndex = 3;</code>
       *
       * <pre>
       *新手引导：功能开启时引导执行计数
       * </pre>
       */
      public boolean hasFuncIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 FuncIndex = 3;</code>
       *
       * <pre>
       *新手引导：功能开启时引导执行计数
       * </pre>
       */
      public int getFuncIndex() {
        return funcIndex_;
      }
      /**
       * <code>optional int32 FuncIndex = 3;</code>
       *
       * <pre>
       *新手引导：功能开启时引导执行计数
       * </pre>
       */
      public Builder setFuncIndex(int value) {
        bitField0_ |= 0x00000004;
        funcIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 FuncIndex = 3;</code>
       *
       * <pre>
       *新手引导：功能开启时引导执行计数
       * </pre>
       */
      public Builder clearFuncIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        funcIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.CSChangeGuideStatus)
    }

    static {
      defaultInstance = new CSChangeGuideStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.CSChangeGuideStatus)
  }

  public interface SCLoginSoftGuideOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool loginPrice = 1;
    /**
     * <code>optional bool loginPrice = 1;</code>
     *
     * <pre>
     *登陆奖励
     * </pre>
     */
    boolean hasLoginPrice();
    /**
     * <code>optional bool loginPrice = 1;</code>
     *
     * <pre>
     *登陆奖励
     * </pre>
     */
    boolean getLoginPrice();

    // optional bool questDaily = 2;
    /**
     * <code>optional bool questDaily = 2;</code>
     *
     * <pre>
     *每日任务
     * </pre>
     */
    boolean hasQuestDaily();
    /**
     * <code>optional bool questDaily = 2;</code>
     *
     * <pre>
     *每日任务
     * </pre>
     */
    boolean getQuestDaily();

    // optional bool relation = 3;
    /**
     * <code>optional bool relation = 3;</code>
     *
     * <pre>
     *将星录
     * </pre>
     */
    boolean hasRelation();
    /**
     * <code>optional bool relation = 3;</code>
     *
     * <pre>
     *将星录
     * </pre>
     */
    boolean getRelation();

    // optional bool lottery = 4;
    /**
     * <code>optional bool lottery = 4;</code>
     *
     * <pre>
     *免费抽奖
     * </pre>
     */
    boolean hasLottery();
    /**
     * <code>optional bool lottery = 4;</code>
     *
     * <pre>
     *免费抽奖
     * </pre>
     */
    boolean getLottery();
  }
  /**
   * Protobuf type {@code game.msg.SCLoginSoftGuide}
   *
   * <pre>
   *玩家登陆软引导
   * </pre>
   */
  public static final class SCLoginSoftGuide extends
      com.google.protobuf.GeneratedMessage
      implements SCLoginSoftGuideOrBuilder {
    // Use SCLoginSoftGuide.newBuilder() to construct.
    private SCLoginSoftGuide(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCLoginSoftGuide(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCLoginSoftGuide defaultInstance;
    public static SCLoginSoftGuide getDefaultInstance() {
      return defaultInstance;
    }

    public SCLoginSoftGuide getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCLoginSoftGuide(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              loginPrice_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              questDaily_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              relation_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lottery_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgGuide.internal_static_game_msg_SCLoginSoftGuide_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgGuide.internal_static_game_msg_SCLoginSoftGuide_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgGuide.SCLoginSoftGuide.class, game.msg.MsgGuide.SCLoginSoftGuide.Builder.class);
    }

    public static com.google.protobuf.Parser<SCLoginSoftGuide> PARSER =
        new com.google.protobuf.AbstractParser<SCLoginSoftGuide>() {
      public SCLoginSoftGuide parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCLoginSoftGuide(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCLoginSoftGuide> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool loginPrice = 1;
    public static final int LOGINPRICE_FIELD_NUMBER = 1;
    private boolean loginPrice_;
    /**
     * <code>optional bool loginPrice = 1;</code>
     *
     * <pre>
     *登陆奖励
     * </pre>
     */
    public boolean hasLoginPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool loginPrice = 1;</code>
     *
     * <pre>
     *登陆奖励
     * </pre>
     */
    public boolean getLoginPrice() {
      return loginPrice_;
    }

    // optional bool questDaily = 2;
    public static final int QUESTDAILY_FIELD_NUMBER = 2;
    private boolean questDaily_;
    /**
     * <code>optional bool questDaily = 2;</code>
     *
     * <pre>
     *每日任务
     * </pre>
     */
    public boolean hasQuestDaily() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool questDaily = 2;</code>
     *
     * <pre>
     *每日任务
     * </pre>
     */
    public boolean getQuestDaily() {
      return questDaily_;
    }

    // optional bool relation = 3;
    public static final int RELATION_FIELD_NUMBER = 3;
    private boolean relation_;
    /**
     * <code>optional bool relation = 3;</code>
     *
     * <pre>
     *将星录
     * </pre>
     */
    public boolean hasRelation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool relation = 3;</code>
     *
     * <pre>
     *将星录
     * </pre>
     */
    public boolean getRelation() {
      return relation_;
    }

    // optional bool lottery = 4;
    public static final int LOTTERY_FIELD_NUMBER = 4;
    private boolean lottery_;
    /**
     * <code>optional bool lottery = 4;</code>
     *
     * <pre>
     *免费抽奖
     * </pre>
     */
    public boolean hasLottery() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool lottery = 4;</code>
     *
     * <pre>
     *免费抽奖
     * </pre>
     */
    public boolean getLottery() {
      return lottery_;
    }

    private void initFields() {
      loginPrice_ = false;
      questDaily_ = false;
      relation_ = false;
      lottery_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, loginPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, questDaily_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, relation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, lottery_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, loginPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, questDaily_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, relation_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, lottery_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.SCLoginSoftGuide parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgGuide.SCLoginSoftGuide prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCLoginSoftGuide}
     *
     * <pre>
     *玩家登陆软引导
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgGuide.SCLoginSoftGuideOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgGuide.internal_static_game_msg_SCLoginSoftGuide_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgGuide.internal_static_game_msg_SCLoginSoftGuide_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgGuide.SCLoginSoftGuide.class, game.msg.MsgGuide.SCLoginSoftGuide.Builder.class);
      }

      // Construct using game.msg.MsgGuide.SCLoginSoftGuide.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        loginPrice_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        questDaily_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        relation_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        lottery_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgGuide.internal_static_game_msg_SCLoginSoftGuide_descriptor;
      }

      public game.msg.MsgGuide.SCLoginSoftGuide getDefaultInstanceForType() {
        return game.msg.MsgGuide.SCLoginSoftGuide.getDefaultInstance();
      }

      public game.msg.MsgGuide.SCLoginSoftGuide build() {
        game.msg.MsgGuide.SCLoginSoftGuide result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgGuide.SCLoginSoftGuide buildPartial() {
        game.msg.MsgGuide.SCLoginSoftGuide result = new game.msg.MsgGuide.SCLoginSoftGuide(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.loginPrice_ = loginPrice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.questDaily_ = questDaily_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.relation_ = relation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lottery_ = lottery_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgGuide.SCLoginSoftGuide) {
          return mergeFrom((game.msg.MsgGuide.SCLoginSoftGuide)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgGuide.SCLoginSoftGuide other) {
        if (other == game.msg.MsgGuide.SCLoginSoftGuide.getDefaultInstance()) return this;
        if (other.hasLoginPrice()) {
          setLoginPrice(other.getLoginPrice());
        }
        if (other.hasQuestDaily()) {
          setQuestDaily(other.getQuestDaily());
        }
        if (other.hasRelation()) {
          setRelation(other.getRelation());
        }
        if (other.hasLottery()) {
          setLottery(other.getLottery());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgGuide.SCLoginSoftGuide parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgGuide.SCLoginSoftGuide) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool loginPrice = 1;
      private boolean loginPrice_ ;
      /**
       * <code>optional bool loginPrice = 1;</code>
       *
       * <pre>
       *登陆奖励
       * </pre>
       */
      public boolean hasLoginPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool loginPrice = 1;</code>
       *
       * <pre>
       *登陆奖励
       * </pre>
       */
      public boolean getLoginPrice() {
        return loginPrice_;
      }
      /**
       * <code>optional bool loginPrice = 1;</code>
       *
       * <pre>
       *登陆奖励
       * </pre>
       */
      public Builder setLoginPrice(boolean value) {
        bitField0_ |= 0x00000001;
        loginPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool loginPrice = 1;</code>
       *
       * <pre>
       *登陆奖励
       * </pre>
       */
      public Builder clearLoginPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        loginPrice_ = false;
        onChanged();
        return this;
      }

      // optional bool questDaily = 2;
      private boolean questDaily_ ;
      /**
       * <code>optional bool questDaily = 2;</code>
       *
       * <pre>
       *每日任务
       * </pre>
       */
      public boolean hasQuestDaily() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool questDaily = 2;</code>
       *
       * <pre>
       *每日任务
       * </pre>
       */
      public boolean getQuestDaily() {
        return questDaily_;
      }
      /**
       * <code>optional bool questDaily = 2;</code>
       *
       * <pre>
       *每日任务
       * </pre>
       */
      public Builder setQuestDaily(boolean value) {
        bitField0_ |= 0x00000002;
        questDaily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool questDaily = 2;</code>
       *
       * <pre>
       *每日任务
       * </pre>
       */
      public Builder clearQuestDaily() {
        bitField0_ = (bitField0_ & ~0x00000002);
        questDaily_ = false;
        onChanged();
        return this;
      }

      // optional bool relation = 3;
      private boolean relation_ ;
      /**
       * <code>optional bool relation = 3;</code>
       *
       * <pre>
       *将星录
       * </pre>
       */
      public boolean hasRelation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool relation = 3;</code>
       *
       * <pre>
       *将星录
       * </pre>
       */
      public boolean getRelation() {
        return relation_;
      }
      /**
       * <code>optional bool relation = 3;</code>
       *
       * <pre>
       *将星录
       * </pre>
       */
      public Builder setRelation(boolean value) {
        bitField0_ |= 0x00000004;
        relation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool relation = 3;</code>
       *
       * <pre>
       *将星录
       * </pre>
       */
      public Builder clearRelation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        relation_ = false;
        onChanged();
        return this;
      }

      // optional bool lottery = 4;
      private boolean lottery_ ;
      /**
       * <code>optional bool lottery = 4;</code>
       *
       * <pre>
       *免费抽奖
       * </pre>
       */
      public boolean hasLottery() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool lottery = 4;</code>
       *
       * <pre>
       *免费抽奖
       * </pre>
       */
      public boolean getLottery() {
        return lottery_;
      }
      /**
       * <code>optional bool lottery = 4;</code>
       *
       * <pre>
       *免费抽奖
       * </pre>
       */
      public Builder setLottery(boolean value) {
        bitField0_ |= 0x00000008;
        lottery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool lottery = 4;</code>
       *
       * <pre>
       *免费抽奖
       * </pre>
       */
      public Builder clearLottery() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lottery_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCLoginSoftGuide)
    }

    static {
      defaultInstance = new SCLoginSoftGuide(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCLoginSoftGuide)
  }

  public interface CSClearGuideStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code game.msg.CSClearGuideStatus}
   *
   * <pre>
   *清除引导状态
   * </pre>
   */
  public static final class CSClearGuideStatus extends
      com.google.protobuf.GeneratedMessage
      implements CSClearGuideStatusOrBuilder {
    // Use CSClearGuideStatus.newBuilder() to construct.
    private CSClearGuideStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSClearGuideStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSClearGuideStatus defaultInstance;
    public static CSClearGuideStatus getDefaultInstance() {
      return defaultInstance;
    }

    public CSClearGuideStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSClearGuideStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgGuide.internal_static_game_msg_CSClearGuideStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgGuide.internal_static_game_msg_CSClearGuideStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgGuide.CSClearGuideStatus.class, game.msg.MsgGuide.CSClearGuideStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<CSClearGuideStatus> PARSER =
        new com.google.protobuf.AbstractParser<CSClearGuideStatus>() {
      public CSClearGuideStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSClearGuideStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSClearGuideStatus> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.CSClearGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgGuide.CSClearGuideStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.CSClearGuideStatus}
     *
     * <pre>
     *清除引导状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgGuide.CSClearGuideStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgGuide.internal_static_game_msg_CSClearGuideStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgGuide.internal_static_game_msg_CSClearGuideStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgGuide.CSClearGuideStatus.class, game.msg.MsgGuide.CSClearGuideStatus.Builder.class);
      }

      // Construct using game.msg.MsgGuide.CSClearGuideStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgGuide.internal_static_game_msg_CSClearGuideStatus_descriptor;
      }

      public game.msg.MsgGuide.CSClearGuideStatus getDefaultInstanceForType() {
        return game.msg.MsgGuide.CSClearGuideStatus.getDefaultInstance();
      }

      public game.msg.MsgGuide.CSClearGuideStatus build() {
        game.msg.MsgGuide.CSClearGuideStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgGuide.CSClearGuideStatus buildPartial() {
        game.msg.MsgGuide.CSClearGuideStatus result = new game.msg.MsgGuide.CSClearGuideStatus(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgGuide.CSClearGuideStatus) {
          return mergeFrom((game.msg.MsgGuide.CSClearGuideStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgGuide.CSClearGuideStatus other) {
        if (other == game.msg.MsgGuide.CSClearGuideStatus.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgGuide.CSClearGuideStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgGuide.CSClearGuideStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.CSClearGuideStatus)
    }

    static {
      defaultInstance = new CSClearGuideStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.CSClearGuideStatus)
  }

  public interface SCClearGuideStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool guideClose = 1;
    /**
     * <code>optional bool guideClose = 1;</code>
     */
    boolean hasGuideClose();
    /**
     * <code>optional bool guideClose = 1;</code>
     */
    boolean getGuideClose();
  }
  /**
   * Protobuf type {@code game.msg.SCClearGuideStatus}
   *
   * <pre>
   *返回引导状态
   * </pre>
   */
  public static final class SCClearGuideStatus extends
      com.google.protobuf.GeneratedMessage
      implements SCClearGuideStatusOrBuilder {
    // Use SCClearGuideStatus.newBuilder() to construct.
    private SCClearGuideStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCClearGuideStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCClearGuideStatus defaultInstance;
    public static SCClearGuideStatus getDefaultInstance() {
      return defaultInstance;
    }

    public SCClearGuideStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCClearGuideStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              guideClose_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgGuide.internal_static_game_msg_SCClearGuideStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgGuide.internal_static_game_msg_SCClearGuideStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgGuide.SCClearGuideStatus.class, game.msg.MsgGuide.SCClearGuideStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<SCClearGuideStatus> PARSER =
        new com.google.protobuf.AbstractParser<SCClearGuideStatus>() {
      public SCClearGuideStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCClearGuideStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCClearGuideStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool guideClose = 1;
    public static final int GUIDECLOSE_FIELD_NUMBER = 1;
    private boolean guideClose_;
    /**
     * <code>optional bool guideClose = 1;</code>
     */
    public boolean hasGuideClose() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool guideClose = 1;</code>
     */
    public boolean getGuideClose() {
      return guideClose_;
    }

    private void initFields() {
      guideClose_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, guideClose_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, guideClose_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgGuide.SCClearGuideStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgGuide.SCClearGuideStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCClearGuideStatus}
     *
     * <pre>
     *返回引导状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgGuide.SCClearGuideStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgGuide.internal_static_game_msg_SCClearGuideStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgGuide.internal_static_game_msg_SCClearGuideStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgGuide.SCClearGuideStatus.class, game.msg.MsgGuide.SCClearGuideStatus.Builder.class);
      }

      // Construct using game.msg.MsgGuide.SCClearGuideStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        guideClose_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgGuide.internal_static_game_msg_SCClearGuideStatus_descriptor;
      }

      public game.msg.MsgGuide.SCClearGuideStatus getDefaultInstanceForType() {
        return game.msg.MsgGuide.SCClearGuideStatus.getDefaultInstance();
      }

      public game.msg.MsgGuide.SCClearGuideStatus build() {
        game.msg.MsgGuide.SCClearGuideStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgGuide.SCClearGuideStatus buildPartial() {
        game.msg.MsgGuide.SCClearGuideStatus result = new game.msg.MsgGuide.SCClearGuideStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guideClose_ = guideClose_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgGuide.SCClearGuideStatus) {
          return mergeFrom((game.msg.MsgGuide.SCClearGuideStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgGuide.SCClearGuideStatus other) {
        if (other == game.msg.MsgGuide.SCClearGuideStatus.getDefaultInstance()) return this;
        if (other.hasGuideClose()) {
          setGuideClose(other.getGuideClose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgGuide.SCClearGuideStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgGuide.SCClearGuideStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool guideClose = 1;
      private boolean guideClose_ ;
      /**
       * <code>optional bool guideClose = 1;</code>
       */
      public boolean hasGuideClose() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool guideClose = 1;</code>
       */
      public boolean getGuideClose() {
        return guideClose_;
      }
      /**
       * <code>optional bool guideClose = 1;</code>
       */
      public Builder setGuideClose(boolean value) {
        bitField0_ |= 0x00000001;
        guideClose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool guideClose = 1;</code>
       */
      public Builder clearGuideClose() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guideClose_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCClearGuideStatus)
    }

    static {
      defaultInstance = new SCClearGuideStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCClearGuideStatus)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_CSChangeGuideStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_CSChangeGuideStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCLoginSoftGuide_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCLoginSoftGuide_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_CSClearGuideStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_CSClearGuideStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCClearGuideStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCClearGuideStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017msg.guide.proto\022\010game.msg\032\roptions.pro" +
      "to\032\014define.proto\"Z\n\023CSChangeGuideStatus\022" +
      "\022\n\nOrderIndex\030\001 \001(\005\022\025\n\rCurFunctionId\030\002 \001" +
      "(\005\022\021\n\tFuncIndex\030\003 \001(\005:\005\210\303\032\201\031\"d\n\020SCLoginS" +
      "oftGuide\022\022\n\nloginPrice\030\001 \001(\010\022\022\n\nquestDai" +
      "ly\030\002 \001(\010\022\020\n\010relation\030\003 \001(\010\022\017\n\007lottery\030\004 " +
      "\001(\010:\005\210\303\032\213\031\"\033\n\022CSClearGuideStatus:\005\210\303\032\214\031\"" +
      "/\n\022SCClearGuideStatus\022\022\n\nguideClose\030\001 \001(" +
      "\010:\005\210\303\032\215\031"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_msg_CSChangeGuideStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_msg_CSChangeGuideStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_CSChangeGuideStatus_descriptor,
              new java.lang.String[] { "OrderIndex", "CurFunctionId", "FuncIndex", });
          internal_static_game_msg_SCLoginSoftGuide_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_msg_SCLoginSoftGuide_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCLoginSoftGuide_descriptor,
              new java.lang.String[] { "LoginPrice", "QuestDaily", "Relation", "Lottery", });
          internal_static_game_msg_CSClearGuideStatus_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_game_msg_CSClearGuideStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_CSClearGuideStatus_descriptor,
              new java.lang.String[] { });
          internal_static_game_msg_SCClearGuideStatus_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_game_msg_SCClearGuideStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCClearGuideStatus_descriptor,
              new java.lang.String[] { "GuideClose", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.msg.Options.getDescriptor(),
          game.msg.Define.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
