// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.platform.proto

package game.msg;

public final class MsgPlatform {
  private MsgPlatform() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CSCheckGiftCodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string code = 1;
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code game.msg.CSCheckGiftCode}
   *
   * <pre>
   *提交礼包激活码
   * </pre>
   */
  public static final class CSCheckGiftCode extends
      com.google.protobuf.GeneratedMessage
      implements CSCheckGiftCodeOrBuilder {
    // Use CSCheckGiftCode.newBuilder() to construct.
    private CSCheckGiftCode(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSCheckGiftCode(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSCheckGiftCode defaultInstance;
    public static CSCheckGiftCode getDefaultInstance() {
      return defaultInstance;
    }

    public CSCheckGiftCode getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CSCheckGiftCode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              code_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgPlatform.internal_static_game_msg_CSCheckGiftCode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgPlatform.internal_static_game_msg_CSCheckGiftCode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgPlatform.CSCheckGiftCode.class, game.msg.MsgPlatform.CSCheckGiftCode.Builder.class);
    }

    public static com.google.protobuf.Parser<CSCheckGiftCode> PARSER =
        new com.google.protobuf.AbstractParser<CSCheckGiftCode>() {
      public CSCheckGiftCode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSCheckGiftCode(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CSCheckGiftCode> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private java.lang.Object code_;
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string code = 1;</code>
     *
     * <pre>
     *激活码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgPlatform.CSCheckGiftCode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgPlatform.CSCheckGiftCode prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.CSCheckGiftCode}
     *
     * <pre>
     *提交礼包激活码
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgPlatform.CSCheckGiftCodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgPlatform.internal_static_game_msg_CSCheckGiftCode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgPlatform.internal_static_game_msg_CSCheckGiftCode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgPlatform.CSCheckGiftCode.class, game.msg.MsgPlatform.CSCheckGiftCode.Builder.class);
      }

      // Construct using game.msg.MsgPlatform.CSCheckGiftCode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgPlatform.internal_static_game_msg_CSCheckGiftCode_descriptor;
      }

      public game.msg.MsgPlatform.CSCheckGiftCode getDefaultInstanceForType() {
        return game.msg.MsgPlatform.CSCheckGiftCode.getDefaultInstance();
      }

      public game.msg.MsgPlatform.CSCheckGiftCode build() {
        game.msg.MsgPlatform.CSCheckGiftCode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgPlatform.CSCheckGiftCode buildPartial() {
        game.msg.MsgPlatform.CSCheckGiftCode result = new game.msg.MsgPlatform.CSCheckGiftCode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgPlatform.CSCheckGiftCode) {
          return mergeFrom((game.msg.MsgPlatform.CSCheckGiftCode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgPlatform.CSCheckGiftCode other) {
        if (other == game.msg.MsgPlatform.CSCheckGiftCode.getDefaultInstance()) return this;
        if (other.hasCode()) {
          bitField0_ |= 0x00000001;
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgPlatform.CSCheckGiftCode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgPlatform.CSCheckGiftCode) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string code = 1;
      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 1;</code>
       *
       * <pre>
       *激活码
       * </pre>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.CSCheckGiftCode)
    }

    static {
      defaultInstance = new CSCheckGiftCode(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.CSCheckGiftCode)
  }

  public interface SCCheckGiftCodeReturnOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 result = 1;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *成功码
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *成功码
     * </pre>
     */
    int getResult();

    // repeated .game.msg.DProduce produceList = 2;
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    java.util.List<game.msg.Define.DProduce> 
        getProduceListList();
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    game.msg.Define.DProduce getProduceList(int index);
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    int getProduceListCount();
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    java.util.List<? extends game.msg.Define.DProduceOrBuilder> 
        getProduceListOrBuilderList();
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    game.msg.Define.DProduceOrBuilder getProduceListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code game.msg.SCCheckGiftCodeReturn}
   *
   * <pre>
   *激活码返回
   * </pre>
   */
  public static final class SCCheckGiftCodeReturn extends
      com.google.protobuf.GeneratedMessage
      implements SCCheckGiftCodeReturnOrBuilder {
    // Use SCCheckGiftCodeReturn.newBuilder() to construct.
    private SCCheckGiftCodeReturn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SCCheckGiftCodeReturn(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SCCheckGiftCodeReturn defaultInstance;
    public static SCCheckGiftCodeReturn getDefaultInstance() {
      return defaultInstance;
    }

    public SCCheckGiftCodeReturn getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SCCheckGiftCodeReturn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                produceList_ = new java.util.ArrayList<game.msg.Define.DProduce>();
                mutable_bitField0_ |= 0x00000002;
              }
              produceList_.add(input.readMessage(game.msg.Define.DProduce.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          produceList_ = java.util.Collections.unmodifiableList(produceList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.msg.MsgPlatform.internal_static_game_msg_SCCheckGiftCodeReturn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.msg.MsgPlatform.internal_static_game_msg_SCCheckGiftCodeReturn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.msg.MsgPlatform.SCCheckGiftCodeReturn.class, game.msg.MsgPlatform.SCCheckGiftCodeReturn.Builder.class);
    }

    public static com.google.protobuf.Parser<SCCheckGiftCodeReturn> PARSER =
        new com.google.protobuf.AbstractParser<SCCheckGiftCodeReturn>() {
      public SCCheckGiftCodeReturn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SCCheckGiftCodeReturn(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SCCheckGiftCodeReturn> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *成功码
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 result = 1;</code>
     *
     * <pre>
     *成功码
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    // repeated .game.msg.DProduce produceList = 2;
    public static final int PRODUCELIST_FIELD_NUMBER = 2;
    private java.util.List<game.msg.Define.DProduce> produceList_;
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    public java.util.List<game.msg.Define.DProduce> getProduceListList() {
      return produceList_;
    }
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    public java.util.List<? extends game.msg.Define.DProduceOrBuilder> 
        getProduceListOrBuilderList() {
      return produceList_;
    }
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    public int getProduceListCount() {
      return produceList_.size();
    }
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    public game.msg.Define.DProduce getProduceList(int index) {
      return produceList_.get(index);
    }
    /**
     * <code>repeated .game.msg.DProduce produceList = 2;</code>
     *
     * <pre>
     * 兑换码奖励	
     * </pre>
     */
    public game.msg.Define.DProduceOrBuilder getProduceListOrBuilder(
        int index) {
      return produceList_.get(index);
    }

    private void initFields() {
      result_ = 0;
      produceList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      for (int i = 0; i < produceList_.size(); i++) {
        output.writeMessage(2, produceList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      for (int i = 0; i < produceList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, produceList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.msg.MsgPlatform.SCCheckGiftCodeReturn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.msg.MsgPlatform.SCCheckGiftCodeReturn prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game.msg.SCCheckGiftCodeReturn}
     *
     * <pre>
     *激活码返回
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.msg.MsgPlatform.SCCheckGiftCodeReturnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.msg.MsgPlatform.internal_static_game_msg_SCCheckGiftCodeReturn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.msg.MsgPlatform.internal_static_game_msg_SCCheckGiftCodeReturn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.msg.MsgPlatform.SCCheckGiftCodeReturn.class, game.msg.MsgPlatform.SCCheckGiftCodeReturn.Builder.class);
      }

      // Construct using game.msg.MsgPlatform.SCCheckGiftCodeReturn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProduceListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (produceListBuilder_ == null) {
          produceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          produceListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.msg.MsgPlatform.internal_static_game_msg_SCCheckGiftCodeReturn_descriptor;
      }

      public game.msg.MsgPlatform.SCCheckGiftCodeReturn getDefaultInstanceForType() {
        return game.msg.MsgPlatform.SCCheckGiftCodeReturn.getDefaultInstance();
      }

      public game.msg.MsgPlatform.SCCheckGiftCodeReturn build() {
        game.msg.MsgPlatform.SCCheckGiftCodeReturn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.msg.MsgPlatform.SCCheckGiftCodeReturn buildPartial() {
        game.msg.MsgPlatform.SCCheckGiftCodeReturn result = new game.msg.MsgPlatform.SCCheckGiftCodeReturn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (produceListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            produceList_ = java.util.Collections.unmodifiableList(produceList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.produceList_ = produceList_;
        } else {
          result.produceList_ = produceListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.msg.MsgPlatform.SCCheckGiftCodeReturn) {
          return mergeFrom((game.msg.MsgPlatform.SCCheckGiftCodeReturn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.msg.MsgPlatform.SCCheckGiftCodeReturn other) {
        if (other == game.msg.MsgPlatform.SCCheckGiftCodeReturn.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (produceListBuilder_ == null) {
          if (!other.produceList_.isEmpty()) {
            if (produceList_.isEmpty()) {
              produceList_ = other.produceList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProduceListIsMutable();
              produceList_.addAll(other.produceList_);
            }
            onChanged();
          }
        } else {
          if (!other.produceList_.isEmpty()) {
            if (produceListBuilder_.isEmpty()) {
              produceListBuilder_.dispose();
              produceListBuilder_ = null;
              produceList_ = other.produceList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              produceListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProduceListFieldBuilder() : null;
            } else {
              produceListBuilder_.addAllMessages(other.produceList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.msg.MsgPlatform.SCCheckGiftCodeReturn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.msg.MsgPlatform.SCCheckGiftCodeReturn) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 result = 1;
      private int result_ ;
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *成功码
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *成功码
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *成功码
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 1;</code>
       *
       * <pre>
       *成功码
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }

      // repeated .game.msg.DProduce produceList = 2;
      private java.util.List<game.msg.Define.DProduce> produceList_ =
        java.util.Collections.emptyList();
      private void ensureProduceListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          produceList_ = new java.util.ArrayList<game.msg.Define.DProduce>(produceList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          game.msg.Define.DProduce, game.msg.Define.DProduce.Builder, game.msg.Define.DProduceOrBuilder> produceListBuilder_;

      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public java.util.List<game.msg.Define.DProduce> getProduceListList() {
        if (produceListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(produceList_);
        } else {
          return produceListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public int getProduceListCount() {
        if (produceListBuilder_ == null) {
          return produceList_.size();
        } else {
          return produceListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public game.msg.Define.DProduce getProduceList(int index) {
        if (produceListBuilder_ == null) {
          return produceList_.get(index);
        } else {
          return produceListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder setProduceList(
          int index, game.msg.Define.DProduce value) {
        if (produceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProduceListIsMutable();
          produceList_.set(index, value);
          onChanged();
        } else {
          produceListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder setProduceList(
          int index, game.msg.Define.DProduce.Builder builderForValue) {
        if (produceListBuilder_ == null) {
          ensureProduceListIsMutable();
          produceList_.set(index, builderForValue.build());
          onChanged();
        } else {
          produceListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder addProduceList(game.msg.Define.DProduce value) {
        if (produceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProduceListIsMutable();
          produceList_.add(value);
          onChanged();
        } else {
          produceListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder addProduceList(
          int index, game.msg.Define.DProduce value) {
        if (produceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProduceListIsMutable();
          produceList_.add(index, value);
          onChanged();
        } else {
          produceListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder addProduceList(
          game.msg.Define.DProduce.Builder builderForValue) {
        if (produceListBuilder_ == null) {
          ensureProduceListIsMutable();
          produceList_.add(builderForValue.build());
          onChanged();
        } else {
          produceListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder addProduceList(
          int index, game.msg.Define.DProduce.Builder builderForValue) {
        if (produceListBuilder_ == null) {
          ensureProduceListIsMutable();
          produceList_.add(index, builderForValue.build());
          onChanged();
        } else {
          produceListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder addAllProduceList(
          java.lang.Iterable<? extends game.msg.Define.DProduce> values) {
        if (produceListBuilder_ == null) {
          ensureProduceListIsMutable();
          super.addAll(values, produceList_);
          onChanged();
        } else {
          produceListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder clearProduceList() {
        if (produceListBuilder_ == null) {
          produceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          produceListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public Builder removeProduceList(int index) {
        if (produceListBuilder_ == null) {
          ensureProduceListIsMutable();
          produceList_.remove(index);
          onChanged();
        } else {
          produceListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public game.msg.Define.DProduce.Builder getProduceListBuilder(
          int index) {
        return getProduceListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public game.msg.Define.DProduceOrBuilder getProduceListOrBuilder(
          int index) {
        if (produceListBuilder_ == null) {
          return produceList_.get(index);  } else {
          return produceListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public java.util.List<? extends game.msg.Define.DProduceOrBuilder> 
           getProduceListOrBuilderList() {
        if (produceListBuilder_ != null) {
          return produceListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(produceList_);
        }
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public game.msg.Define.DProduce.Builder addProduceListBuilder() {
        return getProduceListFieldBuilder().addBuilder(
            game.msg.Define.DProduce.getDefaultInstance());
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public game.msg.Define.DProduce.Builder addProduceListBuilder(
          int index) {
        return getProduceListFieldBuilder().addBuilder(
            index, game.msg.Define.DProduce.getDefaultInstance());
      }
      /**
       * <code>repeated .game.msg.DProduce produceList = 2;</code>
       *
       * <pre>
       * 兑换码奖励	
       * </pre>
       */
      public java.util.List<game.msg.Define.DProduce.Builder> 
           getProduceListBuilderList() {
        return getProduceListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          game.msg.Define.DProduce, game.msg.Define.DProduce.Builder, game.msg.Define.DProduceOrBuilder> 
          getProduceListFieldBuilder() {
        if (produceListBuilder_ == null) {
          produceListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              game.msg.Define.DProduce, game.msg.Define.DProduce.Builder, game.msg.Define.DProduceOrBuilder>(
                  produceList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          produceList_ = null;
        }
        return produceListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:game.msg.SCCheckGiftCodeReturn)
    }

    static {
      defaultInstance = new SCCheckGiftCodeReturn(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:game.msg.SCCheckGiftCodeReturn)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_CSCheckGiftCode_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_CSCheckGiftCode_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_msg_SCCheckGiftCodeReturn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_msg_SCCheckGiftCodeReturn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022msg.platform.proto\022\010game.msg\032\roptions." +
      "proto\032\014define.proto\"&\n\017CSCheckGiftCode\022\014" +
      "\n\004code\030\001 \001(\t:\005\210\303\032\245&\"W\n\025SCCheckGiftCodeRe" +
      "turn\022\016\n\006result\030\001 \001(\005\022\'\n\013produceList\030\002 \003(" +
      "\0132\022.game.msg.DProduce:\005\210\303\032\246&"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_msg_CSCheckGiftCode_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_msg_CSCheckGiftCode_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_CSCheckGiftCode_descriptor,
              new java.lang.String[] { "Code", });
          internal_static_game_msg_SCCheckGiftCodeReturn_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_msg_SCCheckGiftCodeReturn_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_msg_SCCheckGiftCodeReturn_descriptor,
              new java.lang.String[] { "Result", "ProduceList", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(game.msg.Options.msgid);
          registry.add(game.msg.Options.msgid);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.msg.Options.getDescriptor(),
          game.msg.Define.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
